repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1" # Available tags: https://github.com/pre-commit/mirrors-prettier/tags
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.8.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint-plugin-react@7.28.0
          - eslint-plugin-react-native@4.0.0
